name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install Poetry
        run: pipx install poetry
      - name: Install deps
        run: poetry install --no-interaction --no-root
      - name: Ruff
        run: poetry run ruff check .
      - name: Black
        run: poetry run black --check .
      - name: Mypy
        run: poetry run mypy --strict .
      - name: Pytest
        run: poetry run pytest -q
